### ISSUE TITLE
Which branch?

### ISSUE THREAD

**Issue by polkovnikov-ph** [johnyob/dromedary#49]
Chapter 3.2.1 of a thesis mentions a `src/constraints` folder, which is absent in `master` branch. There are several other branches that have this folder.

- Is there a branch that corresponds to thesis?
- Was there a change in architecture that made `src/constraints` obsolete afterwards?

**Comment by johnyob** [comment]
Hey 👋 Yes, the repository was restructured after I wrote my dissertation. 

It was updated in b61b3ff7bbd5e5aeb0ddc4ccdc67931a84043227. 
You can view the repository (as described in the dissertation) at 730e1b95231b1fe3294005ff2be9059f3c856678.

**Comment by polkovnikov-ph** [comment]
Thanks!
